// Code generated by templ@v0.2.334 DO NOT EDIT.

package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/c7/todo.c7.se/todo"

func EditItemForm(item *todo.Item) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"block py-2 border-b-4 border-dotted border-red-900 draggable\"><button disabled=\"disabled\" class=\"mr-2\">")
		if err != nil {
			return err
		}
		var_2 := `❌`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><button disabled=\"disabled\" class=\"mr-2\">")
		if err != nil {
			return err
		}
		var_3 := `📝`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button><input type=\"hidden\" name=\"id\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(item.ID.String()))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><form method=\"POST\" action=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString("/items/" + item.ID.String() + "/edit"))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"closest div\" hx-swap=\"outerHTML\" hx-patch=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString("/items/" + item.ID.String()))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" class=\"inline\"><input type=\"hidden\" name=\"completed\"")
		if err != nil {
			return err
		}
		if item.Completed {
			_, err = templBuffer.WriteString(" value=\"true\"")
			if err != nil {
				return err
			}
		} else {
			_, err = templBuffer.WriteString(" value=\"false\"")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("><input type=\"text\" name=\"description\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(item.Description))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><input type=\"submit\" class=\"hidden\"></form></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
