// Code generated by templ@v0.2.334 DO NOT EDIT.

package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/c7/todo.c7.se/todo"

func List(list todo.List) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<form hx-post=\"/items/sort\" hx-trigger=\"end\" class=\"block p-0 mb-2 text-lg\"><div id=\"items\" class=\" sortable\">")
		if err != nil {
			return err
		}
		for _, item := range list {
			err = Item(item).Render(ctx, templBuffer)
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("<div id=\"no-items\" class=\"hidden first:block first:pb-2 first:pt-3\"><p>")
		if err != nil {
			return err
		}
		var_2 := `Congrats, you have no more TODO items! Or... do you? 🤔`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</p></div></div></form>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
