// Code generated by templ@v0.2.334 DO NOT EDIT.

package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Search(term string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<form method=\"GET\" action=\"/todos\" class=\"inline [&amp;:has(+ul:empty)]:hidden\"><label class=\"flex items-center\"><span class=\"text-lg font-bold\">")
		if err != nil {
			return err
		}
		var_2 := `Search`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</span><input id=\"search\" name=\"search\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(term))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" type=\"text\" placeholder=\"Begin typing to search...\" hx-get=\"/todos\" hx-target=\"#todos\" hx-trigger=\"keyup changed, search\" hx-replace=\"innerHTML\" class=\"ml-2 grow\"></label></form>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
